image: debian:testing

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -y build-essential python3:any binfmt-support btrfs-progs dmsetup dosfstools git kpartx parted psmisc python3-cliapp pxz qemu-user-static qemu-utils sshpass sudo u-boot-tools vmdebootstrap
  - apt-get build-dep -y .

stages:
  - test
  - package

run-unit-tests:
  stage: test
  script:
    - python3 setup.py test

build-debian-package:
  stage: package
  script:
    - DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -us -uc -b
    - mkdir debian-package
    - mv ../freedom-maker*.deb debian-package

  artifacts:
    paths:
      - debian-package/*
